version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/omnidata
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - omnidata_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./:/app
    networks:
      - omnidata_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=omnidata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - omnidata_network

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://postgres:postgres@db:5432/omnidata
    depends_on:
      - db
    networks:
      - omnidata_network

  airflow:
    image: apache/airflow:2.7.2
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:postgres@db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - omnidata_network

volumes:
  postgres_data:


networks:
  omnidata_network:
    driver: bridge
