version: '3.8'

services:
  backend:
    build: .
    ports:
      - "6006:6006"
    env_file:
      - .env
    volumes:
      - ./scrollintel:/app/scrollintel
    depends_on:
      - redis
      - db
    command: uvicorn scrollintel.api.main:app --host 0.0.0.0 --port 6006 --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-scrollintel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-scrollintel}
      POSTGRES_DB: ${POSTGRES_DB:-scrollintel}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
