version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scrollintel
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGINS=${DOMAIN_NAME:-http://localhost:8501}
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - APP_NAME=ScrollIntel
      - APP_VERSION=v2
      - INTERPRETER_TYPE=Flame
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./scrollintel:/app/scrollintel
    networks:
      - scrollintel-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - APP_NAME=ScrollIntel
      - APP_VERSION=v2
      - INTERPRETER_TYPE=Flame
    volumes:
      - ./scrollintel:/app/scrollintel
      - /app/node_modules
    networks:
      - scrollintel-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scrollintel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scrollintel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scrollintel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  redis_data:

networks:
  scrollintel-network:
    driver: bridge
